# -*- coding: utf-8 -*-
"""FRAME_EXTRACTION_FROM_MP4_VIDEO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y28V8OUdqphGvTCqoezNg4XgoB2-QX2n
"""

pip install opencv-python

"""Import the open cv library -cv2 and the os module"""

import cv2
import os

"""To read the input file and VideoCapture('video path') is the function used here"""

cam= cv2.VideoCapture('/content/2019 Singapore Open MS final - badminton Highlights _ Momota vs Ginting.mp4')

import cv2
import os


from logging import currentframe as logging_currentframe

try:

    if not os.path.exists('data'):
        os.makedirs('data')

except OSError:
    print("Error:Creating Directory of Data")

logging_currentframe=0

while(True):

   ret,frame=cam.read()

   if ret:

    name ='./data/frame' + str(logging_currentframe) +".jpg"

    print("Creating..."+name)

    cv2.imwrite(name,frame)

    logging_currentframe +=1

   else:
       break

cam.release()
cv2.destroyAllWindows()