# -*- coding: utf-8 -*-
"""frame_extraction_with_touch_event.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQGeF7cCpnnt4sLsXXLJDON8NHq9peKl
"""

import cv2
import pygame
import os

def extract_frame_on_click(video_path, output_folder):

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    pygame.init()
    screen = pygame.display.set_mode((640, 480))

    video = cv2.VideoCapture(video_path)


    if not video.isOpened():
        print(f"Error: Could not open video {video_path}")
        return

    frame_count = 0
    saved_count = 0
    paused = False

    while True:

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                video.release()
                pygame.quit()
                return

            if event.type == pygame.MOUSEBUTTONDOWN:
                paused = True
                print("Touch event detected. Saving the current frame...")

        if not paused:
            ret, frame = video.read()
            if not ret:
                break

            cv2.imshow('Video Frame', frame)
            frame_count += 1

        else:

            frame_name = f"{output_folder}/frame_{saved_count:05d}.jpg"
            cv2.imwrite(frame_name, frame)
            saved_count += 1
            paused = False

        if cv2.waitKey(20) & 0xFF == ord('q'):
            break

    video.release()
    cv2.destroyAllWindows()
    pygame.quit()
    print(f"Extracted and saved {saved_count} frames to {output_folder}")


video_path = ''  # enter your video path
output_folder = 'extracted_frames'
extract_frame_on_click(video_path, output_folder)